// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBU6Os_mFCvly8EK4g3_O5KV2OM6hv0I',
    appId: '1:7903887033:web:8194d4d17627ec44772568',
    messagingSenderId: '7903887033',
    projectId: 'currentaffair-87a45',
    authDomain: 'currentaffair-87a45.firebaseapp.com',
    storageBucket: 'currentaffair-87a45.firebasestorage.app',
    measurementId: 'G-HZ1T8W27KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCac0-NEZsIe_W_HGF47om127bnOo1fQsc',
    appId: '1:7903887033:android:d53a47d31ac20254772568',
    messagingSenderId: '7903887033',
    projectId: 'currentaffair-87a45',
    storageBucket: 'currentaffair-87a45.firebasestorage.app',
  );
}
